name: Deploy app to Cloudflare Pages

on:
  push:
    branches: ["master"]
    paths:
      - 'app/**'
      - '.github/workflows/static-sites.yml'
  workflow_dispatch:

permissions:
  contents: read
  deployments: write

concurrency:
  group: "cf-pages-app"
  cancel-in-progress: true

jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Publish to Cloudflare Pages (Wrangler)
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy app --project-name=${{ vars.CF_PAGES_PROJECT_NAME }}
